name: movie_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.6
  lottie: ^1.3.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.15
  flutter_animated_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_tmdb.svg
    - assets/lottie/movieLottie.json
    - assets/lottie/icons8_search_white.json
    - assets/lottie/icons8_search.json
    - .env
